version: '3.8'
services:
  crowdar.react:
    image: crowdar.react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app:cached
    container_name: crowdar.frontend
    command: >
      bash -c "
        pnpm i && pnpm run dev "
