version: "3.8"
services:

  crowdar.django:
    image: crowdar.django
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app:cached
    ports:
      - "8001:8001"
    container_name: crowdar.backend
    command: >
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate && 
        python manage.py runserver 0.0.0.0:8001"