# Generated by Django 4.0.6 on 2022-07-24 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_detalledocumento_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_owner', to='base.owner'),
        ),
    ]
