# Generated by Django 4.0.6 on 2022-07-24 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_documento_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.owner'),
        ),
    ]
