# Generated by Django 4.0.6 on 2022-07-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_documento_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
