# Generated by Django 4.0.6 on 2022-07-25 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_documento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocumento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='base.documento'),
        ),
    ]
